version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_PATH: /data/runs.sqlite
      # The UI can be accessed from localhost or 127.0.0.1
      ALLOWED_ORIGINS: "http://localhost:8501,http://127.0.0.1:8501"
    ports:
      - "8001:8000"
    volumes:
      - runs_data:/data

  ui:
    build:
      context: ..
      dockerfile: frontend/streamlit_app/Dockerfile
    environment:
      API_URL: "http://api:8000"
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  runs_data:
    driver: local

