name: CI
on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt pytest requests
      - run: pytest -q -k "not integration"  # unit tests (no API needed)

  integration:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: chmod +x tests/integration_compose.sh
      - run: echo "OPENAI_API_KEY is set? ${{ env.OPENAI_API_KEY != '' }}"
      - run: tests/integration_compose.sh
